### ISSUE TITLE
[gymcms/hero] - take 5 hero doesn't present well for some resolutions

### ISSUE THREAD

**Issue by mbifulco** [gymnasium/tracker#35]
**URL where bug occurs (if applicable)**
thegymnasium.com (home)

**To Reproduce**
As reported by Susie Hall this evening:

> There may be something I don't understand, but the left hand side of the home page looks odd (in al 3 browsers I tried):
![image](https://user-images.githubusercontent.com/1844496/76040525-92cfbe80-5f1d-11ea-95de-3587edae221f.png)

After some investigation, this is an approx 1170px resolution - the default for a 13" Macbook Pro.

**Expected behavior**
We should do our best not to clip/crop the image-side of the hero at any resolution.

**Screenshots**
☝️ see above

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] -- Chrome, Safari, Firefox

**Comment by jgagne** [comment]
Happy to sort out breakpoints and image crop guidelines for a better user experience.

**Comment by andrewpmiller** [comment]
@jgagne or @mbifulco — did this get resolved?

**Comment by mbifulco** [comment]
Not yet

**Comment by jgagne** [comment]
@andrewpmiller and @mbifulco — I'll work on this issue.

**Comment by andrewpmiller** [comment]
I know that this was an issue that was specifically apparent with the Figma hero... and we don't have any near-term plans to re-feature it. I'd just noticed this issue was still in "Needs Triage" but didn't know if perhaps the fix had been implemented with a subsequent hero design (and the issue didn't get auto-resolved). I wasn't suggesting that it needed to be prioritized... just asking if it had been resolved so that we could close the issue 😉
