### ISSUE TITLE
Catalog content for GYM-106 (Dataviz) is not correct

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#73]
Catalog content for the "dataviz" course is not correct. The title of the course is **Information Design & Visualization Fundamentals** - the short description of the course refers to the title as "Information Design & Data Visualization Fundamentals" (the errant "Data") needs to be removed.

![image](https://user-images.githubusercontent.com/5747506/83811440-d1ddef00-a687-11ea-943f-a0273f2b7f00.png)

Staging: https://courses.gymna.si/courses/GYM/106/staging/about
Production: https://thegymnasium.com/courses/GYM/106/0/about

**This must be fixed in Studio**

Settings > Schedule & Details > Course Overview

**Staging:** https://studio.gymna.si/settings/details/GYM/106/staging
**Production:** https://studio.thegymnasium.com/settings/details/GYM/106/0

**NOTE:** The following gymcms data file needs to be updated with the correct title as well — `_data/courses/GYM-106.yml`

**Comment by jgagne** [comment]
Studio course title update is visible on both staging and production.

Staging: https://courses.gymna.si/courses/GYM/106/staging/about
Production: https://thegymnasium.com/courses/G.M/106/0/about

**Before**

![gym-106-data-before](https://user-images.githubusercontent.com/5142085/87211822-59eb9000-c2e9-11ea-83bc-271ccb17441d.png)

**After**

![gym-106-no-data-after](https://user-images.githubusercontent.com/5142085/87211829-5fe17100-c2e9-11ea-9ae8-d307ea2c3b9c.png)

**Notes:**
- The section heading below "Course Preview" was updated to "About This Course" to avoid any further course title confusion or drift, using a more generic, yet consistent title that appears elsewhere on other full courses
- All course assets are linked to assets on GitHub instead of Dropbox

**Comment by jgagne** [comment]
Studio course title update is visible on both staging and production.

Staging: https://courses.gymna.si/courses/GYM/106/staging/about
Production: https://thegymnasium.com/courses/G.M/106/0/about

**Before**

![gym-106-data-before](https://user-images.githubusercontent.com/5142085/87211822-59eb9000-c2e9-11ea-83bc-271ccb17441d.png)

**After**

![gym-106-no-data-after](https://user-images.githubusercontent.com/5142085/87211829-5fe17100-c2e9-11ea-9ae8-d307ea2c3b9c.png)

**Notes:**
- The section heading below "Course Preview" was updated to "About This Course" to avoid any further course title confusion or drift, using a more generic, yet consistent title that appears elsewhere on other full courses
- All course assets are linked to assets on GitHub instead of Dropbox

**Comment by andrewpmiller** [comment]
- course title has been updated to use the **ampersand** in studio on staging and production
- yaml has been updated to use the ampersand
